language: java
jdk:
- openjdk8
services:
  docker
branches:
  only:
  - master
script: mvn test -B -Dspring.profiles.active=test
env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}
     - REPO=$DOCKER_USERNAME/chuck-service
before_install:
# install heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
after_success:
- mvn deploy:deploy-file -Durl="$MAVEN_REPOSITORY_NAME" -DrepositoryId="$MAVEN_REPOSITORY_URL"  -Dfile=./target/chuck-service-0.1.0-stubs.jar -Dclassifier=stubs -DgroupId=com.springboot.docker -DartifactId=chuck-service -Dversion=0.1.0
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
- docker push $REPO
# Token from heroku auth:token
- docker login -u "$HEROKU_USER" -p "$HEROKU_PASSWORD" registry.heroku.com
- docker build -t registry.heroku.com/chuck-service/web .
- docker push registry.heroku.com/chuck-service/web
- heroku container:release web --app chuck-service

