language: java
jdk:
- oraclejdk8
services:
  docker
branches:
  only:
  - master
script: mvn test -B -Dspring.profiles.active=test
env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}
     - REPO=$DOCKER_USERNAME/chuck-service
     - HEROKU_REPO=$DOCKER_USERNAME/chuck-service
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
- docker push $REPO
# Token from heroku auth:token
- docker login -u="$HEROKU_USER" -password="$HEROKU_PASSWORD" registry.heroku.com
- docker build -t registry.heroku.com/chuck-service/web .
- docker push registry.heroku.com/chuck-service/web

